name: Build market-history (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"   # כל יום ב-02:15 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy

      - name: Run builder
        run: |
          python scripts/build_history.py
          ls -la history
          test -f market-history.json && echo "OK: market-history.json exists"

      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          add: "history/*.csv market-history.json"
          message: "chore(history): update CSV + market-history.json"
