name: Build market-history (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"   # כל לילה 02:15 UTC

permissions:
  contents: write   # כדי שנוכל לבצע commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build history (CSV + JSON)
        run: |
          python scripts/build_history.py
          ls -l history | cat
          test -f market-history.json && echo "market-history.json created ✔"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add history/*.csv market-history.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update history CSVs + market-history.json"
            git push
          fi
