name: Build market-history (daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"  # כל יום 03:17 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build market-history.json
        run: |
          python scripts/build_history.py

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add market-history.json
          git commit -m "chore: update market-history.json [skip ci]" || echo "No changes to commit"
          git push
